services:
  frontend:
    image: docker.io/sythinian/open-stream-hub-frontend:latest # TODO: not latest
    depends_on:
      - backend
    ports:
      - "80:80" # Frontend server port
    environment:
      - VITE_REST_API_HOST=http://${PRIVATE_IP}:6636
    networks:
      - internal
    restart: unless-stopped
  backend:
    image: docker.io/sythinian/open-stream-hub-backend:latest # TODO: not latest
    depends_on:
      - mongodb
    ports:
      - "6636:6636" # REST API server port
      - "1935:1935" # RTMP server port
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/open-stream-hubV2
      - REST_API_PORT=6636
      - RTMP_SERVER_PORT=1935
      - RTMP_INJECT_HOST=rtmp://${OSH_RTMP_DOMAIN}
      - RTMP_INJECT_ROOT=/inject
      - RTMP_WATCH_ROOT=/watch
      - HSL_PREVIEW_ENABLED=true
    networks:
      - internal
    restart: unless-stopped
  mongodb:
    image: docker.io/library/mongo:latest # TODO: not latest
    volumes:
      - "mongodb-data-vol:/data/db:Z"
    networks:
      - internal
    restart: unless-stopped
networks:
  internal:
volumes:
  mongodb-data-vol:
